import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center items-center mt-32 flex-col ">
         <h3 className='text-3xl'>  start your project right now 🚀!</h3>
        <div className='flex justify-center space-x-2 items-center mt-10'>
        <div className=' bg-yellow-400 p-10 '>
             next js 
         </div>
         <div className=' bg-yellow-400 p-10 '>
              context api 
         </div><div className=' bg-yellow-400 p-10 '>
             tailwin css 
         </div><div className=' bg-yellow-400 p-10 '>
              axios 
         </div>
        </div>
        <Link className='mt-[20rem] text-blue-500' href='/blog'>blog </Link>
      </main>

      
    </>
  )
}
